name: Build/release

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.3.4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Compile webpack scripts
        run: npm run compile

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
        if: startsWith(github.ref, 'refs/tags/v')

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          args: -l AppImage

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
        if: matrix.os == 'ubuntu-latest' && startsWith(github.ref, 'refs/tags/v')

      # - name: Publish artifacts on ubuntu
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: xbox-xcloud-electron-linux.deb
      #     path: |
      #       dist/*.deb
      #   if: matrix.os == 'ubuntu-latest' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))

      # - name: Publish artifacts on osx
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: xbox-xcloud-electron-osx.dmg
      #     path: |
      #       dist/*.dmg
      #   if: matrix.os == 'macos-latest' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))

      # - name: Publish artifacts on windows
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: xbox-xcloud-electron-windows.zip
      #     path: |
      #       dist/*.exe
      #   if: matrix.os == 'windows-latest' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))